### ISSUE TITLE
Add support for 1.19.4

### ISSUE THREAD

**Issue by RinixGG** [EngineHub/WorldEditCUI#90] opened 2023-03-18 19:58 UTC
### The Problem

Current version is crashing on 1.19.4 when joining a world (worldedit works fine)
Here is the [log](https://mclo.gs/7BkPSmK)

### A Solution

Add support for 1.19.4

**Comment by zml2008** [comment] 2023-03-18 20:05
Duplicate of #87

**Closed by zml2008** 2023-03-18 20:05 UTC
Labels: enhancement
