### ISSUE TITLE
Clearing selection with keystroke crashes the game

### ISSUE THREAD

**Issue by GoldEmberMage** [EngineHub/WorldEditCUI#78] opened 2022-11-05 15:31 UTC
### WorldEditCUI Version

1.19+01

### Fabric Version

0.11.1

### Fabric API Version

0.64.0+1.19.2

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEditCUI compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.

### Bug Description

When I press my assigned key to clear the WorldEdit selection, the game saves, then promptly crashes. This is in singleplayer. Here's my crash log:
[crash-2022-11-05_10.19.31-client.txt](https://github.com/EngineHub/WorldEditCUI/files/9944135/crash-2022-11-05_10.19.31-client.txt)

### Expected Behavior

The keystroke is supposed to clear the WorldEdit selection

### Reproduction Steps

1. Assign the "Clear WorldEdit Selection" Keystroke to _anything_
2. Press that keystroke ingame in singleplayer with a region selected

**Comment by zml2008** [comment] 2022-11-05 15:58
Duplicate of #70

**Closed by zml2008** 2022-11-05 15:58 UTC
Labels: bug
