### ISSUE TITLE
Port the mod to 1.21!

### ISSUE THREAD

**Issue by HardRedux** [EngineHub/WorldEditCUI#121] opened 2024-10-16 05:09 UTC
### The Problem

Port the mod to 1.21!

### A Solution

Port the mod to 1.21!

### Alternatives

Port the mod to 1.21!

### Anything Else?

Port the mod to 1.21!

**Comment by zml2008** [comment] 2024-10-16 05:25
duplicate of many issues

**Closed by zml2008** 2024-10-16 05:25 UTC
Labels: enhancement
