### ISSUE TITLE
Error when clearing selection with hotkey

### ISSUE THREAD

**Issue by SolidBlock-cn** [EngineHub/WorldEditCUI#75] opened 2022-10-08 04:58 UTC
### WorldEditCUI Version

1.19+01

### Fabric Version

Fabric 0.14.9

### Fabric API Version

0.62.0+1.19.2

### Confirmations

- [X] I am using the most recent Minecraft release.
- [X] I am using a version of WorldEditCUI compatible with my Minecraft version.
- [X] I am using the latest or recommended version of my platform software.

### Bug Description

If I set a hotkey of clearing selection region and click that hotkey, MC crashes.

### Expected Behavior

Clear the selection.

### Reproduction Steps

1. ...
2. ...

**Comment by SolidBlock-cn** [comment] 2022-10-08 05:02
```
Description: Unexpected error

java.lang.NoSuchMethodError: 'void net.minecraft.class_746.method_44099(java.lang.String)'
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)
	at org.enginehub.worldeditcui.fabric.FabricModWorldEditCUI.onTick(FabricModWorldEditCUI.java:124)
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:65)
	at net.minecraft.client.MinecraftClient.handler$zjk000$onEndTick(MinecraftClient:5473)
	at net.minecraft.client.MinecraftClient.tick(MinecraftClient:1907)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1135)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:768)
	at net.minecraft.client.main.Main.method_44604(Main:244)
	at net.minecraft.client.main.Main.main(Main:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

**Comment by me4502** [comment] 2022-10-08 05:04
Duplicate of https://github.com/EngineHub/WorldEditCUI/issues/70

**Closed by me4502** 2022-10-08 05:04 UTC
Labels: bug
